version: "3.5"
services:
  php:
    build:
      dockerfile: .docker/php/Dockerfile
      context: .
      args:
        - UID=1000
        - GID=1000
    volumes:
      - ./:/app
      - /app/public/storage
    networks:
      - web
  webserver:
    build:
      dockerfile: .docker/nginx/Dockerfile
      context: .
    ports:
      - 8000:80
    volumes:
      - .:/app
      - /app/public/storage
      - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - web
  composer:
    image: composer:latest
    volumes:
        - ./:/app
        - ./.composer:/composer
networks:
  web:
